name: Build Project and Deploy to GHPages
on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        name: Build & deploy
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Build
              id: build
              uses: manleydev/build-godot-action@v1.4.1
              with:
                  name: godot-pong
                  preset: HTML5

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: build
